const express = require("express");
const router = express.Router();

// DATA
const APP_SERVICES = [
      { icon: '📱', title: 'React Native App Development', note: 'iOS & Android from one codebase', partTag: 'App Dev', price: '₹1.2 Lakh', desc: 'Build beautiful, high-performance apps for iOS and Android using a single React Native codebase. Reduce development cost and time without sacrificing native fe.', features: ['Cross-platform iOS & Android', 'Native UI components & animations', 'Push notifications & deep links', 'Offline-first architecture', 'Biometric auth (Face ID / Fingerprint)', 'App Store & Play Store submission'], chips: ['MVP in 3–5 weeks', 'Social Login', 'Payment Integration', 'Analytics'], subServices: [{ icon: '📲', label: 'iOS Build', note: 'App Store ready' }, { icon: '🤖', label: 'Android Build', note: 'Play Store ready' }, { icon: '🔔', label: 'Push Notifications', note: 'FCM & APNs' }, { icon: '💳', label: 'Payments', note: 'Razorpay/UPI' }, { icon: '📊', label: 'Analytics', note: 'Firebase' }, { icon: '🔐', label: 'Biometric Auth', note: 'Face ID/Touch' }] },
      { icon: '🐦', title: 'Flutter App Development', note: 'Beautiful native apps — Google Flutter', partTag: 'App Dev', price: '₹1.1 Lakh', desc: 'Flutter enables pixel-perfect UI on both iOS and Android with a single codebase. Ideal for apps where visual design and animation quality matter most.', features: ['Single codebase for iOS, Android & Web', 'Custom animations & transitions', 'Material Design & Cupertino widgets', 'Firebase & REST API integration', 'Background services & notifications', 'Hot reload for fast development'], chips: ['Smooth Animations', 'Rich UI', 'Web Support', 'Fast Build'], subServices: [{ icon: '🎨', label: 'Custom UI', note: 'Pixel perfect' }, { icon: '🔥', label: 'Firebase', note: 'Backend ready' }, { icon: '🌐', label: 'Web Support', note: 'Same codebase' }, { icon: '🔄', label: 'State Mgmt', note: 'Riverpod/Bloc' }, { icon: '📦', label: 'Packages', note: 'Pub.dev' }, { icon: '🧪', label: 'Testing', note: 'Unit & widget' }] },
      { icon: '🍎', title: 'iOS App Development (Swift)', note: 'Native iPhone & iPad apps', partTag: 'App Dev', price: '₹1.5 Lakh', desc: 'Pure native iOS apps using Swift and SwiftUI — best choice for complex apps demanding maximum performance, deep iOS integration and App Store success.', features: ['Swift & SwiftUI development', 'Core Data & CloudKit storage', 'HealthKit, ARKit, MapKit integration', 'Apple Pay & StoreKit', 'Watch & iPad companion apps', 'TestFlight beta testing & release'], chips: ['SwiftUI', 'ARKit', 'HealthKit', 'Apple Pay'], subServices: [{ icon: '⌚', label: 'Watch App', note: 'WatchOS' }, { icon: '📱', label: 'iPad App', note: 'Universal' }, { icon: '🏥', label: 'HealthKit', note: 'Health data' }, { icon: '💰', label: 'Apple Pay', note: 'StoreKit' }, { icon: '🗺️', label: 'MapKit', note: 'Location' }, { icon: '🔬', label: 'ARKit', note: 'Augmented Reality' }] },
      { icon: '🤖', title: 'Android App Development (Kotlin)', note: 'Native Android apps for all devices', partTag: 'App Dev', price: '₹1.2 Lakh', desc: 'Native Android development with Kotlin — the modern, safer language endorsed by Google. Apps that work across the entire Android ecosystem.', features: ['Kotlin & Jetpack Compose', 'Room database & LiveData', 'Google Maps & Location services', 'FCM push notifications', 'Google Pay & Billing API', 'Adaptive layouts for all screens'], chips: ['Jetpack Compose', 'Google Pay', 'Kotlin Coroutines', 'Play Store'], subServices: [{ icon: '🗺️', label: 'Google Maps', note: 'Location services' }, { icon: '💳', label: 'Google Pay', note: 'Billing API' }, { icon: '🔔', label: 'FCM', note: 'Push notifications' }, { icon: '🗄️', label: 'Room DB', note: 'Local storage' }, { icon: '🎨', label: 'Compose UI', note: 'Modern UI kit' }, { icon: '⚡', label: 'Coroutines', note: 'Async operations' }] },
      { icon: '📦', title: 'MVP App Development', note: 'Launch fast, validate your idea', partTag: 'App Dev', price: '₹60K', desc: 'Build your minimum viable product in 3–5 weeks. Launch lean, get real user feedback, and iterate fast before committing to the full product build.', features: ['Core feature development only', 'Basic UI with clean design', 'User auth & onboarding flow', 'Cloud backend (Firebase/Supabase)', 'Analytics & crash reporting setup', 'App Store / Play Store submission'], chips: ['3–5 Week Delivery', 'Lean Budget', 'User Feedback', 'Iterate Fast'], subServices: [{ icon: '🚀', label: 'Fast Launch', note: '3–5 weeks' }, { icon: '🔑', label: 'Auth & Login', note: 'Social + email' }, { icon: '☁️', label: 'Cloud Backend', note: 'Firebase' }, { icon: '📊', label: 'Analytics', note: 'Mixpanel/Firebase' }, { icon: '🐛', label: 'Crash Reports', note: 'Sentry' }, { icon: '🏪', label: 'Store Submit', note: 'Both stores' }] },
      { icon: '🛒', title: 'E-Commerce Mobile App', note: 'Online store on iOS & Android', partTag: 'App Dev', price: '₹1.5 Lakh', desc: 'Custom mobile shopping apps with product catalogues, cart, checkout, UPI/card payments and real-time order tracking built for D2C brands and marketplaces.', features: ['Product catalogue & search', 'Shopping cart & wishlist', 'UPI, Razorpay, PayU payments', 'Real-time order tracking', 'Push notification for offers', 'Admin panel for inventory'], chips: ['UPI Payment', 'Order Tracking', 'Push Offers', 'Admin Panel'], subServices: [{ icon: '🛍️', label: 'Product Catalog', note: 'Search & filter' }, { icon: '🛒', label: 'Cart & Checkout', note: 'Smooth UX' }, { icon: '💳', label: 'UPI & Cards', note: 'Razorpay' }, { icon: '📦', label: 'Order Tracking', note: 'Real-time' }, { icon: '🔔', label: 'Offer Alerts', note: 'Push notifications' }, { icon: '🖥️', label: 'Admin Panel', note: 'Inventory' }] },
      { icon: '🎓', title: 'EdTech App', note: 'Learning & education platforms', partTag: 'App Dev', price: '₹1.3 Lakh', desc: 'Mobile learning apps with video courses, live classes, quizzes, progress tracking and certifications — designed to maximize engagement and learning outcomes.', features: ['Video player with adaptive streaming', 'Live class scheduling (Zoom/custom)', 'Quiz engine with AI scoring', 'Progress tracking & badges', 'Instructor & admin panels', 'Multi-language support'], chips: ['Video Courses', 'Live Classes', 'AI Quiz', 'Gamification'], subServices: [{ icon: '🎬', label: 'Video Player', note: 'Adaptive stream' }, { icon: '🎥', label: 'Live Classes', note: 'Zoom/custom' }, { icon: '🧠', label: 'AI Quiz', note: 'Smart scoring' }, { icon: '🏆', label: 'Badges', note: 'Gamification' }, { icon: '👩‍🏫', label: 'Instructor Panel', note: 'Dashboard' }, { icon: '🌏', label: 'Multi-lang', note: 'Hindi & more' }] },
    ];


const WEB_SERVICES = [
      { icon: '🌐', title: 'Corporate Website', note: 'Professional, fast & SEO-optimised', partTag: 'Web Dev', price: '₹40K', desc: 'Clean, modern corporate websites built on Next.js or WordPress — SEO-ready, mobile-responsive, and designed to establish credibility and generate leads.', features: ['Responsive multi-page design', 'Blog & news section (CMS)', 'Contact forms & lead capture', 'SEO on-page optimisation', 'Google Analytics integration', 'Fast loading (Core Web Vitals)'], chips: ['SEO Ready', 'CMS', 'Lead Forms', 'Fast Loading'], subServices: [{ icon: '📱', label: 'Responsive', note: 'All devices' }, { icon: '✍️', label: 'CMS Blog', note: 'Easy editing' }, { icon: '📊', label: 'Analytics', note: 'Google Analytics' }, { icon: '🔍', label: 'SEO', note: 'On-page ready' }, { icon: '📝', label: 'Lead Forms', note: 'Contact forms' }, { icon: '⚡', label: 'Fast Load', note: 'Core Web Vitals' }] },
      { icon: '🛍️', title: 'E-Commerce Website', note: 'Custom stores, Shopify & headless', partTag: 'Web Dev', price: '₹1.2 Lakh', desc: 'From Shopify stores to fully custom Next.js storefronts — we build e-commerce sites that are conversion-optimised, fast and deeply integrated with Indian payments.', features: ['Custom or headless storefront', 'Product catalogue & filtering', 'Cart, checkout & order management', 'Razorpay, UPI, COD payments', 'Abandoned cart recovery', 'Inventory & shipping management'], chips: ['Headless Commerce', 'Razorpay', 'Inventory', 'SEO'], subServices: [{ icon: '🏪', label: 'Storefront', note: 'Custom design' }, { icon: '🔍', label: 'Product Filter', note: 'Advanced search' }, { icon: '💳', label: 'Razorpay', note: 'Indian payments' }, { icon: '📦', label: 'Inventory', note: 'Stock management' }, { icon: '🛒', label: 'Cart Recovery', note: 'Abandoned cart' }, { icon: '🚚', label: 'Shipping', note: 'Courier APIs' }] },
      { icon: '📊', title: 'SaaS Platform / Dashboard', note: 'Full-stack SaaS applications', partTag: 'Web Dev', price: '₹2.5 Lakh', desc: 'Build your SaaS product from scratch — multi-tenant architecture, subscription billing, user roles, analytics dashboards and everything needed to run a cloud business.', features: ['Multi-tenant architecture', 'Stripe / Razorpay subscription billing', 'Role-based access control (RBAC)', 'Real-time data dashboards', 'API-first, headless backend', 'Scalable to 1M+ users'], chips: ['Multi-Tenant', 'Stripe Billing', 'Real-time', 'API-First'], subServices: [{ icon: '🏢', label: 'Multi-tenant', note: 'SaaS ready' }, { icon: '💰', label: 'Billing', note: 'Stripe/Razorpay' }, { icon: '👥', label: 'RBAC', note: 'User roles' }, { icon: '📈', label: 'Dashboards', note: 'Real-time charts' }, { icon: '🔗', label: 'API-First', note: 'REST & GraphQL' }, { icon: '📧', label: 'Email Flows', note: 'Transactional' }] },
      { icon: '🏫', title: 'LMS / Learning Portal', note: 'Online education & training platforms', partTag: 'Web Dev', price: '₹1.5 Lakh', desc: 'Custom Learning Management Systems for schools, edtech companies and corporates — video courses, assessments, certifications and instructor dashboards.', features: ['Course builder & video hosting', 'Live class scheduling (Zoom/custom)', 'Assessment & certificate engine', 'Student progress dashboards', 'Instructor & admin panels', 'Payment gateway for enrollments'], chips: ['Video Courses', 'Certificates', 'Live Classes', 'Instructor Panel'], subServices: [{ icon: '🎬', label: 'Course Builder', note: 'Video hosting' }, { icon: '📜', label: 'Certificates', note: 'Auto-generated' }, { icon: '📊', label: 'Progress', note: 'Student tracking' }, { icon: '💳', label: 'Enrollment Pay', note: 'Gateway' }, { icon: '👩‍🏫', label: 'Instructor', note: 'Dashboard' }, { icon: '🎥', label: 'Live Classes', note: 'Zoom integration' }] },
      { icon: '🏠', title: 'Real Estate Portal', note: 'Property listing & management sites', partTag: 'Web Dev', price: '₹1.2 Lakh', desc: 'Property listing portals with advanced search, virtual tours, EMI calculators, agent dashboards and CRM integration — for brokers, builders and PropTech startups.', features: ['Advanced property search & filters', 'Map-based property view', 'Virtual tour embed (360°)', 'EMI & affordability calculator', 'Agent & developer dashboards', 'Lead management CRM'], chips: ['Map View', 'Virtual Tours', 'EMI Calc', 'CRM'], subServices: [{ icon: '🗺️', label: 'Map View', note: 'Google Maps' }, { icon: '🔍', label: 'Advanced Search', note: 'Filters' }, { icon: '🏠', label: 'Virtual Tours', note: '360° view' }, { icon: '🧮', label: 'EMI Calc', note: 'Affordability' }, { icon: '👨‍💼', label: 'Agent Panel', note: 'Dashboard' }, { icon: '📋', label: 'Lead CRM', note: 'Tracking' }] },
      { icon: '🚚', title: 'Logistics / Delivery Platform', note: 'Fleet tracking & dispatch systems', partTag: 'Web Dev', price: '₹1.8 Lakh', desc: 'Web-based logistics platforms with real-time fleet tracking, driver management, dispatch control rooms, route optimisation and customer delivery portals.', features: ['Real-time GPS fleet tracking', 'Driver app (React Native)', 'Automated dispatch & routing', 'Customer delivery status portal', 'SLA & performance reports', 'API integration with courier providers'], chips: ['Real-Time GPS', 'Route Optimisation', 'Driver App', 'SLA Reports'], subServices: [{ icon: '📍', label: 'GPS Tracking', note: 'Real-time' }, { icon: '🚗', label: 'Driver App', note: 'React Native' }, { icon: '🗺️', label: 'Route Optim.', note: 'Smart routing' }, { icon: '📊', label: 'SLA Reports', note: 'Performance' }, { icon: '👥', label: 'Customer Portal', note: 'Live updates' }, { icon: '🔗', label: 'Courier APIs', note: 'Integration' }] },
      { icon: '💳', title: 'Fintech Web Platform', note: 'Payments, wallets & lending', partTag: 'Web Dev', price: '₹3 Lakh', desc: 'Secure fintech platforms — payment gateways, digital wallets, KYC workflows, NBFC lending portals and financial dashboards built to RBI and compliance standards.', features: ['Payment gateway integration', 'Digital wallet & UPI flow', 'Video KYC & Aadhaar verification', 'NBFC loan origination system', 'Transaction reconciliation', 'Compliance & audit logs'], chips: ['KYC', 'UPI', 'Wallet', 'Compliance'], subServices: [{ icon: '💳', label: 'Payment GW', note: 'Multi-gateway' }, { icon: '👛', label: 'Digital Wallet', note: 'UPI flow' }, { icon: '🪪', label: 'Video KYC', note: 'Aadhaar' }, { icon: '🏦', label: 'Lending', note: 'NBFC portal' }, { icon: '📋', label: 'Reconciliation', note: 'Auto match' }, { icon: '🔒', label: 'Compliance', note: 'Audit logs' }] },
    ];    


 const OTHER_SERVICES = [
      { icon: '🎨', title: 'UI/UX Design', note: 'Research-backed interfaces ', partTag: 'Design', price: '₹40K', desc: 'Beautiful design is not decoration — it is the difference between a product people love and one they abandon. Our design team starts with user research and delivers pixel-perfect Figma files ready for handoff.', features: ['User research & persona creation', 'Information architecture', 'Low & high-fidelity wireframes', 'Interactive Figma prototypes', 'Usability testing & iteration', 'Design system & component library', 'Developer handoff documentation'], chips: ['User Research', 'Wireframing', 'Figma Prototypes', 'Design Systems'], subServices: [{ icon: '🔍', label: 'UX Research', note: 'User interviews' }, { icon: '📐', label: 'Wireframing', note: 'Fast ideation' }, { icon: '✨', label: 'Visual Design', note: 'Brand-aligned UI' }, { icon: '📱', label: 'Mobile UI', note: 'iOS & Android' }, { icon: '🖥️', label: 'Web UI', note: 'Responsive' }, { icon: '🎭', label: 'Design Systems', note: 'Component libs' }] },
      { icon: '⚙️', title: 'Backend & API Development', note: 'Scalable, secure server infrastructure & APIs', partTag: 'Backend', price: '₹60K', desc: 'Your product is only as good as the engine running it. Our backend engineers design robust, secure, and horizontally scalable architectures that handle millions of requests.', features: ['Node.js, Python, Go, Java', 'REST & GraphQL API design', 'PostgreSQL, MongoDB, Redis, Elasticsearch', 'JWT, OAuth2 & RBAC auth systems', 'Horizontal scaling & load balancing', 'CI/CD pipelines (GitHub Actions)', 'Comprehensive API documentation'], chips: ['REST & GraphQL', 'Microservices', 'Database Design', 'Cloud Infrastructure'], subServices: [{ icon: '🔗', label: 'API Dev', note: 'REST & GraphQL' }, { icon: '🗄️', label: 'Database Design', note: 'SQL & NoSQL' }, { icon: '☁️', label: 'Cloud Setup', note: 'AWS/GCP/Azure' }, { icon: '🔒', label: 'Security Audit', note: 'Pen testing' }, { icon: '📈', label: 'Scaling Infra', note: '1M+ users' }, { icon: '🔄', label: 'Legacy Migration', note: 'Modernise' }] },
      { icon: '🚀', title: 'DevOps & Cloud Services', note: 'CI/CD, cloud infra and reliability engineering', partTag: 'DevOps', price: '₹50K', desc: 'Bring new code and features to your products painlessly. We help you reduce time to market without sacrificing reliability, security, and compliance.', features: ['Infrastructure as Code (Terraform)', 'Kubernetes & Docker', 'GitHub Actions, Jenkins CI/CD', 'AWS, GCP, Azure multi-cloud', 'Monitoring (Prometheus, Grafana)', 'ELK Stack log management', 'Disaster recovery & backup'], chips: ['Cloud Infrastructure', 'CI/CD Services', 'Cost Optimisation', 'Kubernetes & Docker'], subServices: [{ icon: '🐳', label: 'Containerisation', note: 'Docker & K8s' }, { icon: '🔄', label: 'CI/CD Pipelines', note: 'Automate deploys' }, { icon: '☁️', label: 'Cloud Migration', note: 'Lift & shift' }, { icon: '💸', label: 'Cost Optimisation', note: 'Cut bills 30–60%' }, { icon: '📊', label: 'Monitoring', note: 'Full observability' }, { icon: '🛡️', label: 'Security & IAM', note: 'Zero-trust' }] },
      { icon: '🤖', title: 'AI & Machine Learning', note: 'Intelligent features, chatbots & automation', partTag: 'AI / ML', price: '₹1 Lakh', desc: 'We integrate AI into your products to automate workflows, personalise experiences and unlock data insights. From OpenAI integrations to custom ML models — we make AI practical and profitable.', features: ['OpenAI, Gemini & Claude integrations', 'Custom ML model training', 'Natural language processing (NLP)', 'Computer vision & image recognition', 'Recommendation engines', 'Robotic process automation (RPA)', 'MLOps & model monitoring'], chips: ['LLM Integration', 'Computer Vision', 'Recommendation Engines', 'RPA Automation'], subServices: [{ icon: '💬', label: 'AI Chatbots', note: 'GPT-powered' }, { icon: '👁️', label: 'Computer Vision', note: 'Image & video AI' }, { icon: '🎯', label: 'Recommendation', note: 'Personalised UX' }, { icon: '📊', label: 'Predictive Analytics', note: 'Forecast' }, { icon: '📝', label: 'NLP Solutions', note: 'Text & speech' }, { icon: '🔧', label: 'RPA & Automation', note: 'Workflow bots' }] },
      { icon: '👨‍💻', title: 'Hire Dedicated Developers', note: 'Expert engineers, monthly', partTag: 'Hire Dev', price: '₹80K/mo', desc: 'Need dedicated engineering talent without the overhead of full-time hiring? Hire our pre-vetted developers on a monthly basis — they work in your tools, your timezone, and your workflow.', features: ['Pre-vetted senior engineers (3–8 yr exp)', 'Daily stand-ups & sprint participation', 'Work in your tools (Jira, Slack, GitHub)', 'Flexible engagement', 'Dedicated project manager', 'Weekly progress reports', 'Replace or scale anytime — no lock-ins'], chips: ['Full-Time Developers', 'Part-Time Developers', 'Team Augmentation', 'CTO as a Service'], subServices: [{ icon: '📱', label: 'React Native Dev', note: 'iOS & Android' }, { icon: '⚛️', label: 'React / Next.js', note: 'Frontend' }, { icon: '🐍', label: 'Python / Django', note: 'Backend & ML' }, { icon: '🟩', label: 'Node.js Dev', note: 'APIs & services' }, { icon: '🐳', label: 'DevOps Engineer', note: 'CI/CD & cloud' }, { icon: '🗄️', label: 'Database Engineer', note: 'SQL & NoSQL' }] },
      { icon: '📰', title: 'News & Media Website', note: 'High-traffic CMS & media portals', partTag: 'Web Dev', price: '₹60K', desc: 'News portals, magazine sites and media platforms built to handle high traffic, fast delivery, editorial workflows, SEO and ad monetisation.', features: ['Headless CMS (Sanity/Contentful)', 'Breaking news real-time feed', 'SEO-optimised article pages', 'Ad network integration (Google AdSense)', 'Email subscription system', 'Multi-author editorial workflow'], chips: ['Headless CMS', 'SEO', 'Ad Monetisation', 'High Traffic'], subServices: [{ icon: '📝', label: 'Headless CMS', note: 'Sanity/Contentful' }, { icon: '⚡', label: 'Breaking News', note: 'Real-time feed' }, { icon: '🔍', label: 'SEO Articles', note: 'Optimised' }, { icon: '💰', label: 'Ad Network', note: 'AdSense' }, { icon: '📧', label: 'Newsletter', note: 'Subscriptions' }, { icon: '✍️', label: 'Multi-author', note: 'Editorial flow' }] },
      { icon: '🔧', title: 'Maintenance & Support', note: 'Post-launch care, updates and 24/7 monitoring', partTag: 'Support', price: '₹15K/mo', desc: "Launching is not the end — it's the beginning. Our maintenance plans ensure your product stays fast, secure and bug-free so you can focus on your business.", features: ['24/7 uptime monitoring & alerts', 'Critical bug fixes (4-hr response SLA)', 'Security patches & dependency updates', 'Monthly performance reports', 'Feature additions & enhancements', 'Database optimisation & cleanup', 'Quarterly security audits'], chips: ['Bug Fixing', 'Security Patches', 'Performance Monitoring', 'Feature Additions'], subServices: [{ icon: '🐛', label: 'Bug Fixing', note: 'Fast turnaround' }, { icon: '🔒', label: 'Security Updates', note: 'Patch & harden' }, { icon: '📊', label: 'Performance Tune', note: 'Speed optim.' }, { icon: '📈', label: 'Feature Dev', note: 'Post-launch adds' }, { icon: '☁️', label: 'Cloud Monitoring', note: '24/7 alerting' }, { icon: '📋', label: 'Monthly Reports', note: 'Full transparency' }] },
    ];    

// ROUTES
router.get("/service", (req, res) => {
  res.render("service/servicepage");
});

router.get("/service2", (req, res) => {
  const { type, id } = req.query;

  console.log("DEBUG:", type, id);

  if (!type || id === undefined) {
    return res.send("Service not found");
  }

  let service;

  if (type === "app") {
    service = APP_SERVICES[id];
  }

  if (type === "web") {
    service =WEB_SERVICES[id];
  }

  if (type === "other") {
    service =OTHER_SERVICES[id];
  }

  if (!service) {
    return res.send("Invalid service");
  }

  res.render("service/servicecontent", { service });
});

module.exports = router;